CREATE TABLE IF NOT EXISTS ntail.forgot_password_request (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
	expired_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_forgot_password_user FOREIGN KEY (user_id) REFERENCES ntail.users(id)
	ON DELETE CASCADE
);